[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --partition-table partitions.csv"

[env]
ESP_LOG="none"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-Z", "stack-protector=all",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
